import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// ✅ 1. Import the ToastContainer and its CSS
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "AI Dropout Predictor",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.jpg",  // or "/my-favicon.png"
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Your page content will be rendered here */}
        {children}
        
        {/* ✅ 2. Add the ToastContainer here to make it available globally */}
        <ToastContainer
            position="top-center"
            autoClose={2000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="light"
        />
      </body>
    </html>
  );
}
